import { imageUrls } from '@/patina/assets/images'

export const boardMembers = [
  {
    name: 'Cinthia Hai Young Kim',
    role: 'Board Member',
    email: 'cinthia@patinanetwork.org',
    linkedInUrl: 'http://www.linkedin.com/in/cinthiahykim',
    webUrl: '',
    githubUrl: '',
    imageSrc: imageUrls.cinthia.src,
  },
  {
    name: 'Andrea Matsudaira',
    role: 'Board Member',
    email: 'andrea@patinanetwork.org',
    linkedInUrl: 'https://www.linkedin.com/in/andreamatsudaira/',
    webUrl: '',
    githubUrl: '',
    imageSrc: imageUrls.andrea.src,
  },
  {
    name: 'Celina Hipolito',
    role: 'Board Member',
    email: 'celina@patinanetwork.org',
    linkedInUrl: 'https://www.linkedin.com/in/celinahipolito/',
    webUrl: '',
    githubUrl: '',
    imageSrc: imageUrls.celina.src,
  },
  {
    name: 'Joan Lee',
    role: 'Board Member',
    email: '',
    linkedInUrl: '',
    webUrl: '',
    githubUrl: '',
    imageSrc: imageUrls.joan.src,
  },
  {
    name: 'Kevin Oh',
    role: 'Board Member',
    email: 'kevin@patinanetwork.org',
    linkedInUrl: 'https://www.linkedin.com/in/kevin-y-oh/',
    webUrl: '',
    githubUrl: '',
    imageSrc: imageUrls.kevin.src,
  },
]

export const advisors = [
  {
    name: 'Sara Bloem',
    role: 'Advisor',
    email: '',
    linkedInUrl: '',
    webUrl: '',
    githubUrl: '',
    imageSrc: imageUrls.sara.src,
  },
  {
    name: 'Henry Chen',
    role: 'SWE Manager',
    email: 'hjc77@cornell.edu',
    linkedInUrl: 'https://www.linkedin.com/in/arklian/',
    webUrl: '',
    githubUrl: 'https://github.com/arklian',
    imageSrc: imageUrls.henry.src,
  },
]

export const interns = [
  {
    name: 'Jasmine Eng',
    role: 'Data Analyst Intern',
    email: 'jfe33@cornell.edu',
    linkedInUrl: 'https://www.linkedin.com/in/jasmineeng5/',
    webUrl: '',
    githubUrl: 'https://github.com/jasminee5',
    imageSrc: imageUrls.jasmine.src,
  },
  {
    name: 'Joy Om',
    role: 'UI/UX Design Intern',
    email: '',
    linkedInUrl: 'https://www.linkedin.com/in/joy-om/',
    webUrl: '',
    githubUrl: '',
    imageSrc: imageUrls.joy.src,
  },
  {
    name: 'Maliha Tasnim',
    role: 'SWE Intern',
    email: 'ayesiddika@gmail.com',
    linkedInUrl: 'https://www.linkedin.com/in/maliha-tasnim-81864b178/',
    webUrl: 'https://patinanetwork.org/personal/maliha/',
    githubUrl: 'https://github.com/MalihaT111',
    imageSrc: imageUrls.maliha.src,
  },
  {
    name: 'Jionghao Wu',
    role: 'SWE Intern',
    email: 'jhwu03@gmail.com',
    linkedInUrl: 'https://www.linkedin.com/in/jionghao-wu/',
    webUrl: 'https://patinanetwork.org/personal/jionghao/',
    githubUrl: 'https://github.com/Jhwu3',
    imageSrc: imageUrls.jionghao.src,
  },
  {
    name: 'Riyuan Liu',
    role: 'SWE Intern',
    email: 'Riyuanliu31@gmail.com',
    linkedInUrl: 'https://www.linkedin.com/in/riyuan-liu/',
    webUrl: 'https://patinanetwork.org/personal/riyuan/',
    githubUrl: 'https://github.com/Riyuanliu',
    imageSrc: imageUrls.riyuan.src,
  },
  {
    name: 'Manuel Reyes',
    role: 'SWE Intern',
    email: 'manuelreyes1241@outlook.com',
    linkedInUrl: 'https://www.linkedin.com/in/manuel-reyes-jr-swe/',
    webUrl: 'https://patinanetwork.org/personal/manny/',
    githubUrl: 'https://github.com/Mreyes1241',
    imageSrc: imageUrls.manuel.src,
  },
  {
    name: 'Amanda Ruan',
    role: 'SWE Intern',
    email: 'amandaruan262@gmail.com',
    linkedInUrl: 'https://www.linkedin.com/in/amandaruan/',
    webUrl: 'https://patinanetwork.org/personal/amanda/',
    githubUrl: 'https://github.com/aruan20',
    imageSrc: imageUrls.amanda.src,
  },
  {
    name: 'Kelly Lin',
    role: 'SWE Intern',
    email: 'kelly.lin89@myhunter.cuny.edu',
    linkedInUrl: 'https://www.linkedin.com/in/kxllylin/',
    webUrl: 'https://patinanetwork.org/personal/kelly/',
    githubUrl: 'https://github.com/Kxlcl',
    imageSrc: imageUrls.kelly.src,
  },
  {
    name: 'Tony Wang',
    role: 'SWE Intern',
    email: 'wangtony4005@gmail.com',
    linkedInUrl: 'https://www.linkedin.com/in/wangtony4005/',
    webUrl: 'https://patinanetwork.org/personal/tony/',
    githubUrl: 'https://github.com/wangtony4005',
    imageSrc: imageUrls.tony.src,
  },
  {
    name: 'Kazi Mansha',
    role: 'SWE Intern',
    email: '',
    linkedInUrl: 'https://www.linkedin.com/in/kazimansha/',
    webUrl: 'https://patinanetwork.org/personal/kazi/',
    githubUrl: 'https://github.com/KaziMansha',
    imageSrc: imageUrls.kazi.src,
  },
  {
    name: 'Haoking Luo',
    role: 'SWE Intern',
    email: 'hao5k6032@gmail.com',
    linkedInUrl: 'https://www.linkedin.com/in/luohk1/',
    webUrl: 'https://patinanetwork.org/personal/haoking/',
    githubUrl: 'https://github.com/luoh00',
    imageSrc: imageUrls.haoking.src,
  },
  {
    name: 'Bryan Zhang',
    role: 'SWE Intern',
    email: 'bryan14916@gmail.com',
    linkedInUrl: 'https://www.linkedin.com/in/bryanzhang14916/',
    webUrl: 'https://patinanetwork.org/personal/bryan/',
    githubUrl: 'https://github.com/bz5989',
    imageSrc: imageUrls.bryan.src,
  },
]
