import { imageUrls } from '@/patina/assets/images'

export const internData = [
  {
    name: 'Jasmine Eng',
    role: 'Data Analyst Intern',
    school: 'Cornell University',
    graduation: 'Dec 2024',
    linkedInURL: 'https://www.linkedin.com/in/jasmineeng5/',
    websiteUrl: '',
    githubUrl: 'https://github.com/jasminee5',
    imageSrc: imageUrls.jasmine.src,
  },
  {
    name: 'Joy Om',
    role: 'UI/UX Design Intern',
    school: 'Cornell University',
    graduation: 'May 2026',
    linkedInURL: 'https://www.linkedin.com/in/joy-om/',
    websiteUrl: '',
    githubUrl: '',
    imageSrc: imageUrls.joy.src,
  },
  {
    name: 'Maliha Tasnim',
    role: 'Software Engineering Intern',
    school: 'Hunter College - CUNY',
    graduation: 'May 2026',
    linkedInURL: 'https://www.linkedin.com/in/maliha-tasnim-81864b178/',
    websiteUrl: 'https://patinanetwork.org/personal/maliha/',
    githubUrl: 'https://github.com/MalihaT111',
    imageSrc: imageUrls.maliha.src,
  },
  {
    name: 'Jionghao Wu',
    role: 'Software Engineering Intern',
    school: 'New York University',
    graduation: 'May 2024',
    linkedInURL: 'https://www.linkedin.com/in/jionghao-wu/',
    websiteUrl: 'https://patinanetwork.org/personal/jionghao/',
    githubUrl: 'https://github.com/Jhwu3',
    imageSrc: imageUrls.jionghao.src,
  },
  {
    name: 'Riyuan Liu',
    role: 'Software Engineering Intern',
    school: 'Hunter College - CUNY',
    graduation: 'May 2025',
    linkedInURL: 'https://www.linkedin.com/in/riyuan-liu/',
    websiteUrl: 'https://riyuanliu.com',
    githubUrl: 'https://github.com/Riyuanliu',
    imageSrc: imageUrls.riyuan.src,
  },
  {
    name: 'Manuel Reyes',
    role: 'Software Engineering Intern',
    school: 'Hunter College - CUNY',
    graduation: 'May 2025',
    linkedInURL: 'https://www.linkedin.com/in/manuel-reyes-jr-swe/',
    websiteUrl: 'https://patinanetwork.org/personal/manny/',
    githubUrl: 'https://github.com/Mreyes1241',
    imageSrc: imageUrls.manuel.src,
  },
  {
    name: 'Amanda Ruan',
    role: 'Software Engineering Intern',
    school: 'Rensselaer Polytechnic Institute',
    graduation: 'May 2025',
    linkedInURL: 'https://www.linkedin.com/in/amandaruan/',
    websiteUrl: 'https://patinanetwork.org/personal/amanda/',
    githubUrl: 'https://github.com/aruan20',
    imageSrc: imageUrls.amanda.src,
  },
  {
    name: 'Kelly Lin',
    role: 'Software Engineering Intern',
    school: 'Hunter College - CUNY',
    graduation: 'Dec 2025',
    linkedInURL: 'https://www.linkedin.com/in/kxllylin/',
    websiteUrl: 'https://patinanetwork.org/personal/kelly/',
    githubUrl: 'https://github.com/Kxlcl',
    imageSrc: imageUrls.kelly.src,
  },
  {
    name: 'Tony Wang',
    role: 'Software Engineering Intern',
    school: 'Hunter College - CUNY',
    graduation: 'Dec 2024',
    linkedInURL: 'https://www.linkedin.com/in/wangtony4005/',
    websiteUrl: 'https://patinanetwork.org/personal/tony/',
    githubUrl: 'https://github.com/wangtony4005',
    imageSrc: imageUrls.tony.src,
  },
  {
    name: 'Kazi Mansha',
    role: 'Software Engineering Intern',
    school: 'Hunter College - CUNY',
    graduation: 'May 2025',
    linkedInURL: 'https://www.linkedin.com/in/kazimansha/',
    websiteUrl: 'https://patinanetwork.org/personal/kazi/',
    githubUrl: 'https://github.com/KaziMansha',
    imageSrc: imageUrls.kazi.src,
  },
  {
    name: 'Haoking Luo',
    role: 'Software Engineering Intern',
    school: 'Rensselaer Polytechnic Institute',
    graduation: 'May 2027',
    linkedInURL: 'https://www.linkedin.com/in/luohk1/',
    websiteUrl: 'https://patinanetwork.org/personal/haoking/',
    githubUrl: 'https://github.com/luoh00',
    imageSrc: imageUrls.haoking.src,
  },
  {
    name: 'Bryan Zhang',
    role: 'Software Engineering Intern',
    school: 'Princeton University',
    graduation: 'May 2026',
    linkedInURL: 'https://www.linkedin.com/in/bryanzhang14916/',
    websiteUrl: 'https://patinanetwork.org/personal/bryan/',
    githubUrl: 'https://github.com/bz5989',
    imageSrc: imageUrls.bryan.src,
  },
]
