name: build-image
run-name: building image on ${{ github.actor }}'s commits
on:
  push:
    branches:
      - main
jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to DigitalOcean Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DO_DOCKER_IMAGE_UPLOAD_PAT }}
          password: ${{ secrets.DO_DOCKER_IMAGE_UPLOAD_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set Timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "America/New_York"

      - name: Set image tags
        run: |
          echo "TIMESTAMP=$(date +%Y.%m.%d-%H.%M.%S)" >> $GITHUB_ENV
          echo "GIT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            registry.digitalocean.com/patina/patina-site:latest
            registry.digitalocean.com/patina/patina-site:${{ env.TIMESTAMP }}
            registry.digitalocean.com/patina/patina-site:${{ env.GIT_SHA }}


